FROM fullstack/packages AS base
ENV NODE_ENV=build

USER node
WORKDIR /app/front

COPY --chown=node:node package.json package-lock.json  ./
RUN npm install --save /app/packages/utils/ && \
    npm ci

FROM base AS development

USER node:node
WORKDIR /app/front

COPY --chown=node:node . .

CMD ["npm", "run", "dev"]